name: DigitalOcean Spaces Action
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Sync DigitalOcean Spaces
        uses: laukstein/do-spaces@main
        env:
          DO_ACCESS: ${{ secrets.DO_ACCESS }}
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
          DO_SECRET: ${{ secrets.DO_SECRET }}
          DO_NAME: deliberation-assets
          DO_REGION: nyc3
